version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - database
      - redis
    env_file:
      - .env
      - .config
    volumes:
      - ./src:/code/src
      - ./alembic:/code/alembic
      - ./alembic.ini:/code/alembic.ini
      - ./logging.ini:/code/logging.ini

  database:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/

  redis:
    image: 'redis:latest'
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/var/lib/redis/data/

volumes:
  postgres-data:
  redis-data:
